### ISSUE TITLE
Code for Pixel-Based Observations (FuRL+DrQ)

### ISSUE THREAD

**Issue by kailugaji** [fuyw/FuRL#7]
Thank you for your highly insightful paper. I deeply appreciate the valuable contribution of the paper, which presents compelling experimental results on pixel-based observations, replacing the original states with pixel-based observations. If it's not too much to ask, would it be possible for me to kindly request the code for this experiment? I understand that sharing code can be a sensitive matter, but I genuinely believe that it would greatly benefit my research work. Thank you for considering my request.

**Comment by fuyw** [comment]
Hello, we are sorry that we didn't save the code for pixel based experiments when we clean the code. The implementation is almost the same as the state based experiments where we just made small changes to the official DrQ's codebase. I might add them back in future when I have time.
